### ISSUE TITLE
Benchmark of voxel hashing performance or speed

### ISSUE THREAD

**Issue by LimHyungTae** [MIT-SPARK/Spatial-Hash#4]
Hello, Lukas, this repository looks good to me.

But it would be wonderful if you also show some benchmarks depending on the map scale, neighboring voxel search, and so forth!

In addition, I'm wondering what's the difference between other hashing libraries, such as [robin-map](https://github.com/Tessil/robin-map) or [unordered_dense](https://github.com/martinus/unordered_dense).

**Comment by Schmluk** [comment]
Hi @LimHyungTae ,

Thanks for checking this out! The hashing itself is actually not the key part of this library, the primary goal was to support voxel-block-hashing that we frequently use with nice interfaces and enough flexibility in the data structures to accommodate the differnt types of multi layer maps we use. The performance seems at least as fast as voxblox when integrated in hydra/khronos. The memory coherency of the blocks should also speed up lookups and processing compared to hashing every voxel. If you find the time to run a performance comparison I'd be very curious to see the result! Also, if we find the hashing (which is really simple right now) to be a limiting factor I'm happy to support a more specialized hash implementation such as the ones you mentioned in the backend of this library (although this potentially requires pulling in more deps, which we tried to avoid).

**Comment by LimHyungTae** [comment]
That sounds nice! Thanks for the answer. 

In the future, it would be great if we show how much the algorithm becomes faster in README.md or somewhere :+1:

**Comment by Schmluk** [comment]
I'd be very curious to know, too! Unfortunately don't have time to run these experiments, if you get around to it I'd be happy to see the results!
